import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { request } from '../../api';

// Types
export interface CollectionPreviewItem {
  title: string;
  url: string;
  thumbnailUrl?: string;
}

export interface SmartCollectionOverview {
  id: string;
  title: string;
  description: string;
  category: string;
  isAutoGenerated: boolean;
  isPinned: boolean;
  itemCount: number;
  previewItems: CollectionPreviewItem[];
}

export interface SmartCollectionDetail {
  id: string;
  title: string;
  description: string;
  category: string;
  isAutoGenerated: boolean;
  isPinned: boolean;
  items: {
    id: string;
    title: string;
    url: string;
    contentType: string;
    thumbnailUrl?: string;
    reasoning: string;
  }[];
}

// Queries
export function useCollections() {
  return useQuery({
    queryKey: ['collections'],
    queryFn: async () => {
      const response = await request('/collections');
      if (response.success === false) throw new Error('Failed to fetch collections');
      return response.data as SmartCollectionOverview[];
    }
  });
}

export function useCollection(id: string) {
  return useQuery({
    queryKey: ['collections', id],
    queryFn: async () => {
      const response = await request(`/collections/${id}`);
      if (response.success === false) throw new Error('Failed to fetch collection detail');
      return response.data as SmartCollectionDetail;
    },
    enabled: !!id
  });
}

// Mutations
export function useGenerateCollections() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async () => {
      const response = await request('/collections/generate-from-recent', {
        method: 'POST'
      });
      return response.data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['collections'] });
    }
  });
}

export function usePinCollection() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      const response = await request(`/collections/${id}/pin`, {
        method: 'POST'
      });
      return response.data;
    },
    onSuccess: (_, id) => {
      queryClient.invalidateQueries({ queryKey: ['collections'] });
      queryClient.invalidateQueries({ queryKey: ['collections', id] });
    }
  });
}
