import { useState, useMemo } from 'react';
import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, LayoutGrid, List, Map as MapIcon, Clock, Sparkles } from 'lucide-react';
import { useCollection } from './api';

import CollectionGrid from './components/CollectionGrid';
import CollectionList from './components/CollectionList';
import CollectionMap from './components/CollectionMap';
import CollectionTimeline from './components/CollectionTimeline';
import ContentDetailModalV2 from '../content-feed/ContentDetailModalV2';

type ViewMode = 'grid' | 'list' | 'map' | 'timeline';

export default function CollectionDetail() {
  const { id } = useParams<{ id: string }>();
  const [viewMode, setViewMode] = useState<ViewMode>('grid');
  const [selectedContentId, setSelectedContentId] = useState<string | null>(null);

  const { data: collection, isLoading, error } = useCollection(id || '');

  const items = useMemo(() => {
    if (!collection?.items) return [];
    return collection.items;
  }, [collection]);

  const ViewIcon = {
    grid: LayoutGrid,
    list: List,
    map: MapIcon,
    timeline: Clock
  }[viewMode];

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-full bg-background">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
      </div>
    );
  }

  if (error || !collection) {
    return (
      <div className="flex flex-col items-center justify-center h-full bg-background text-muted-foreground p-10">
        <h2 className="text-xl font-semibold mb-2">Collection Not Found</h2>
        <Link to="/collections" className="text-primary hover:underline">Return to Collections</Link>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full overflow-hidden bg-background">
      {/* Header */}
      <header className="flex-none px-6 py-6 md:px-10 md:py-8 border-b border-border bg-card/50 z-10">
        <Link to="/collections" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors mb-4">
          <ArrowLeft size={16} /> Back to Collections
        </Link>
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
          <div>
            <div className="flex items-center gap-3">
              <h1 className="text-3xl md:text-4xl font-extrabold tracking-tight text-foreground">
                {collection.title}
              </h1>
              {collection.isAutoGenerated && (
                <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium bg-primary/10 text-primary">
                  <Sparkles size={12} />
                  AI Generated
                </span>
              )}
            </div>
            {collection.description && (
              <p className="text-muted-foreground mt-2 max-w-2xl">{collection.description}</p>
            )}
            <p className="text-muted-foreground mt-2 text-sm">{items.length} items collected</p>
          </div>
          
          {/* View Segmented Control */}
          <div className="flex items-center bg-secondary/50 p-1 rounded-xl w-fit">
            {(['grid', 'list', 'map', 'timeline'] as ViewMode[]).map(mode => {
              const Icon = { grid: LayoutGrid, list: List, map: MapIcon, timeline: Clock }[mode];
              return (
                <button
                  key={mode}
                  onClick={() => setViewMode(mode)}
                  className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all ${
                    viewMode === mode 
                      ? 'bg-background text-foreground shadow-sm' 
                      : 'text-muted-foreground hover:text-foreground hover:bg-background/50'
                  }`}
                >
                  <Icon size={16} />
                  <span className="hidden sm:inline capitalize">{mode}</span>
                </button>
              );
            })}
          </div>
        </div>
      </header>

      {/* Content Area */}
      <main className="flex-1 overflow-y-auto relative p-6 md:p-10">
        {items.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-full text-muted-foreground">
            <ViewIcon size={48} className="mb-4 opacity-20" />
            <p>No items found for this collection yet.</p>
          </div>
        ) : (
          <div className="h-full animate-in fade-in duration-300">
            {viewMode === 'grid' && <CollectionGrid items={items} onSelect={setSelectedContentId} />}
            {viewMode === 'list' && <CollectionList items={items} onSelect={setSelectedContentId} />}
            {viewMode === 'map' && <CollectionMap items={items} onSelect={setSelectedContentId} />}
            {viewMode === 'timeline' && <CollectionTimeline items={items} onSelect={setSelectedContentId} />}
          </div>
        )}
      </main>

      {/* Detail Modal */}
      {selectedContentId && (
        <ContentDetailModalV2 
          contentId={selectedContentId} 
          onClose={() => setSelectedContentId(null)}
        />
      )}
    </div>
  );
}
