using System;
using System.Collections.Generic;
using Cortex.Shared;
using Cortex.Modules.Auth.Entities;
using Cortex.Modules.Search.Entities;

namespace Cortex.Modules.Content.Entities;

public class SmartCollection : BaseEntity
{
    public Guid UserId { get; set; }
    
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    
    public string Category { get; set; } = string.Empty;
    public string SubCategory { get; set; } = string.Empty;
    
    public string SourceType { get; set; } = "AI_GENERATED"; // AI_GENERATED, MANUAL, MERGED
    public double Confidence { get; set; } = 1.0;
    
    public bool IsAutoGenerated { get; set; } = true;
    public bool IsPinned { get; set; } = false;
    public bool IsArchived { get; set; } = false;

    public User User { get; set; } = null!;
    public ICollection<SmartCollectionItem> Items { get; set; } = new List<SmartCollectionItem>();
    public ICollection<SmartCollectionSignal> Signals { get; set; } = new List<SmartCollectionSignal>();
}

public class SmartCollectionItem : BaseEntity
{
    public Guid SmartCollectionId { get; set; }
    public Guid ContentItemId { get; set; }
    
    public string Reasoning { get; set; } = string.Empty; // AI reasoning for why it's in this collection
    
    public SmartCollection Collection { get; set; } = null!;
    public ContentItem Content { get; set; } = null!;
}

public class SmartCollectionSignal : BaseEntity
{
    public Guid SmartCollectionId { get; set; }
    
    public string SignalType { get; set; } = string.Empty; // e.g. LOCATION, BEHAVIOR, INTENT
    public string SignalValue { get; set; } = string.Empty; 
    public double Weight { get; set; }
    
    public SmartCollection Collection { get; set; } = null!;
}
