<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cortex.Application\Cortex.Application.csproj" />
    <ProjectReference Include="..\Cortex.Infrastructure\Cortex.Infrastructure.csproj" />
    <ProjectReference Include="..\Cortex.Persistence\Cortex.Persistence.csproj" />
    <ProjectReference Include="..\Cortex.AI\Cortex.AI.csproj" />
    <ProjectReference Include="..\Cortex.SharedKernel\Cortex.SharedKernel.csproj" />
  </ItemGroup>

</Project>
