using Cortex.Database;
using Cortex.Modules.Content.Entities;
using Cortex.Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using System.Text.Json;
using System.Net.Http;

namespace Cortex.Modules.Content.Controllers;

[ApiController]
[Route("api/v1/collections")]
[Authorize]
public class CollectionsController : ControllerBase
{
    private readonly CortexDbContext _dbContext;
    private readonly IHttpClientFactory _httpClientFactory;

    public CollectionsController(CortexDbContext dbContext, IHttpClientFactory httpClientFactory)
    {
        _dbContext = dbContext;
        _httpClientFactory = httpClientFactory;
    }

    [HttpGet]
    public async Task<IActionResult> GetCollections(CancellationToken ct)
    {
        try
        {
            var userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
            var collections = await _dbContext.SmartCollections
                .Include(c => c.Items)
                    .ThenInclude(i => i.Content)
                .Where(c => c.UserId == userId && !c.IsArchived)
                .OrderByDescending(c => c.CreatedAt)
                .ToListAsync(ct);

            var result = collections.Select(c => new
            {
                Id = c.Id,
                Title = c.Title ?? "Unknown",
                Description = c.Description ?? "",
                Category = c.Category ?? "",
                IsAutoGenerated = c.IsAutoGenerated,
                IsPinned = c.IsPinned,
                ItemCount = c.Items.Count,
                PreviewItems = c.Items.Take(4).Select(i => new { Title = i.Content?.Title ?? "Unknown", Url = i.Content?.OriginalUrl ?? "", ThumbnailUrl = i.Content?.HeroImageUrl })
            });

            return Ok(ApiResponse<object>.Ok(result));
        }
        catch (Exception ex)
        {
            return Ok(ApiResponse<object>.Fail(ex.ToString()));
        }
    }

    [HttpGet("{id}")]
    public async Task<IActionResult> GetCollection(Guid id, CancellationToken ct)
    {
        var userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
        var collection = await _dbContext.SmartCollections
            .Include(c => c.Items)
                .ThenInclude(i => i.Content)
            .Include(c => c.Signals)
            .FirstOrDefaultAsync(c => c.Id == id && c.UserId == userId, ct);

        if (collection == null) return NotFound(ApiResponse<object>.Fail("Collection not found"));

        return Ok(ApiResponse<object>.Ok(new
        {
            Id = collection.Id,
            Title = collection.Title ?? "Unknown",
            Description = collection.Description ?? "",
            Category = collection.Category ?? "",
            IsAutoGenerated = collection.IsAutoGenerated,
            IsPinned = collection.IsPinned,
            Items = collection.Items.Select(i => new {
                Id = i.Id,
                Title = i.Content?.Title ?? "Unknown",
                Url = i.Content?.OriginalUrl ?? "",
                ContentType = i.Content?.PlatformType.ToString() ?? "Unknown",
                ThumbnailUrl = i.Content?.HeroImageUrl,
                Reasoning = i.Reasoning ?? ""
            })
        }));
    }

    [HttpPost("{id}/pin")]
    public async Task<IActionResult> PinCollection(Guid id, CancellationToken ct)
    {
        var userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
        var collection = await _dbContext.SmartCollections.FirstOrDefaultAsync(c => c.Id == id && c.UserId == userId, ct);
        if (collection == null) return NotFound();

        collection.IsPinned = !collection.IsPinned;
        await _dbContext.SaveChangesAsync(ct);
        return Ok(ApiResponse<bool>.Ok(collection.IsPinned));
    }

    [HttpPost("generate-from-recent")]
    public async Task<IActionResult> GenerateFromRecent(CancellationToken ct)
    {
        var userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
        var recentItems = await _dbContext.ContentItems
            .Where(c => c.UserId == userId)
            .OrderByDescending(c => c.CreatedAt)
            .Take(50)
            .ToListAsync(ct);

        var payload = new
        {
            userId = userId.ToString(),
            recentSaves = recentItems.Select(i => new { id = i.Id.ToString(), title = i.Title, category = i.PlatformType.ToString(), tags = new List<string>() })
        };

        var client = _httpClientFactory.CreateClient();
        var aiServiceUrl = Environment.GetEnvironmentVariable("PERSONALIZATION_SERVICE_URL") ?? "http://localhost:8001";
        
        var response = await client.PostAsJsonAsync($"{aiServiceUrl}/api/v1/personalization/collections/generate", payload, ct);
        if (!response.IsSuccessStatusCode) return BadRequest(ApiResponse<object>.Fail("AI service failed"));

        var result = await response.Content.ReadFromJsonAsync<JsonElement>(cancellationToken: ct);
        
        var generated = new List<SmartCollection>();
        if (result.TryGetProperty("collections", out var colls))
        {
            foreach(var c in colls.EnumerateArray())
            {
                var title = c.GetProperty("title").GetString() ?? "New Collection";
                
                // only add if title doesn't exist
                if (await _dbContext.SmartCollections.AnyAsync(x => x.UserId == userId && x.Title == title, ct)) continue;

                var newColl = new SmartCollection
                {
                    UserId = userId,
                    Title = title,
                    Description = c.GetProperty("description").GetString() ?? "",
                    Category = c.GetProperty("category").GetString() ?? "",
                    IsAutoGenerated = true
                };

                foreach(var idStr in c.GetProperty("itemIds").EnumerateArray())
                {
                    if (Guid.TryParse(idStr.GetString(), out var itemId))
                    {
                        newColl.Items.Add(new SmartCollectionItem { ContentItemId = itemId });
                    }
                }
                
                if (newColl.Items.Count >= 2) {
                    _dbContext.SmartCollections.Add(newColl);
                    generated.Add(newColl);
                }
            }
            await _dbContext.SaveChangesAsync(ct);
        }

        return Ok(ApiResponse<object>.Ok(generated.Select(g => new { g.Id, g.Title, ItemCount = g.Items.Count })));
    }
}
