// <auto-generated />
using System;
using Cortex.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Cortex.Database.Migrations
{
    [DbContext(typeof(CortexDbContext))]
    [Migration("20260616191613_AddUserMindset")]
    partial class AddUserMindset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cortex.Modules.Auth.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("Cortex.Modules.Auth.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EmailVerificationCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailVerificationCodeExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PhoneVerificationCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PhoneVerificationCodeExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PushToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RefreshTokenHash")
                        .HasDatabaseName("idx_users_refreshtokenhash");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Cortex.Modules.Auth.Entities.UserActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserActivityLogs", (string)null);
                });

            modelBuilder.Entity("Cortex.Modules.Auth.Entities.UserIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_useridentities_userid");

                    b.HasIndex("AuthProvider", "ProviderId")
                        .IsUnique()
                        .HasDatabaseName("uq_useridentities_provider_providerid");

                    b.ToTable("UserIdentities", (string)null);
                });

            modelBuilder.Entity("Cortex.Modules.Auth.Entities.UserMindset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumptionPreference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FocusAreasJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NarrativeSummary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserMindsets", (string)null);
                });

            modelBuilder.Entity("Cortex.Modules.Content.Entities.ActionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId")
                        .HasDatabaseName("idx_actionitems_contentitemid");

                    b.ToTable("ActionItems", (string)null);
                });

            modelBuilder.Entity("Cortex.Modules.Content.Entities.ContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConsumeTimeMins")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnergyLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HeroImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_contentitems_userid");

                    b.HasIndex("UserId", "OriginalUrl")
                        .IsUnique()
                        .HasDatabaseName("uq_user_url");

                    b.HasIndex("UserId", "EnergyLevel", "IsArchived", "CreatedAt")
                        .HasDatabaseName("idx_contentitems_feed");

                    b.ToTable("ContentItems", (string)null);
                });

            modelBuilder.Entity("Cortex.Modules.Content.Entities.ContentItemTag", b =>
                {
                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("ContentItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ContentItemTags", (string)null);
                });

            modelBuilder.Entity("Cortex.Modules.Content.Entities.ContentPayload", b =>
                {
                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuickSparkSummary")
                        .HasColumnType("text");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("SemanticEmbedding")
                        .HasColumnType("vector(1536)");

                    b.HasKey("ContentItemId");

                    b.HasIndex("SemanticEmbedding")
                        .HasDatabaseName("idx_contentpayloads_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SemanticEmbedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SemanticEmbedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("ContentPayloads", (string)null);
                });

            modelBuilder.Entity("Cortex.Modules.Content.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAIGenerated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Cortex.Modules.Drip.Entities.DripStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("DripTrackId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("MediaEndSec")
                        .HasColumnType("integer");

                    b.Property<int?>("MediaStartSec")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ScheduledFor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("DripTrackId")
                        .HasDatabaseName("idx_dripsteps_trackid");

                    b.ToTable("DripSteps", (string)null);
                });

            modelBuilder.Entity("Cortex.Modules.Drip.Entities.DripTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentDay")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId");

                    b.HasIndex("UserId");

                    b.ToTable("DripTracks", (string)null);
                });

            modelBuilder.Entity("Cortex.Modules.Auth.Entities.Subscription", b =>
                {
                    b.HasOne("Cortex.Modules.Auth.Entities.User", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("Cortex.Modules.Auth.Entities.Subscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cortex.Modules.Auth.Entities.UserActivityLog", b =>
                {
                    b.HasOne("Cortex.Modules.Auth.Entities.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cortex.Modules.Auth.Entities.UserIdentity", b =>
                {
                    b.HasOne("Cortex.Modules.Auth.Entities.User", "User")
                        .WithMany("Identities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cortex.Modules.Auth.Entities.UserMindset", b =>
                {
                    b.HasOne("Cortex.Modules.Auth.Entities.User", "User")
                        .WithOne("Mindset")
                        .HasForeignKey("Cortex.Modules.Auth.Entities.UserMindset", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cortex.Modules.Content.Entities.ActionItem", b =>
                {
                    b.HasOne("Cortex.Modules.Content.Entities.ContentItem", "ContentItem")
                        .WithMany("ActionItems")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentItem");
                });

            modelBuilder.Entity("Cortex.Modules.Content.Entities.ContentItem", b =>
                {
                    b.HasOne("Cortex.Modules.Auth.Entities.User", "User")
                        .WithMany("ContentItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cortex.Modules.Content.Entities.ContentItemTag", b =>
                {
                    b.HasOne("Cortex.Modules.Content.Entities.ContentItem", "ContentItem")
                        .WithMany("ContentItemTags")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cortex.Modules.Content.Entities.Tag", "Tag")
                        .WithMany("ContentItemTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentItem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Cortex.Modules.Content.Entities.ContentPayload", b =>
                {
                    b.HasOne("Cortex.Modules.Content.Entities.ContentItem", "ContentItem")
                        .WithOne("Payload")
                        .HasForeignKey("Cortex.Modules.Content.Entities.ContentPayload", "ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentItem");
                });

            modelBuilder.Entity("Cortex.Modules.Drip.Entities.DripStep", b =>
                {
                    b.HasOne("Cortex.Modules.Drip.Entities.DripTrack", "DripTrack")
                        .WithMany("Steps")
                        .HasForeignKey("DripTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DripTrack");
                });

            modelBuilder.Entity("Cortex.Modules.Drip.Entities.DripTrack", b =>
                {
                    b.HasOne("Cortex.Modules.Content.Entities.ContentItem", "ContentItem")
                        .WithMany("DripTracks")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cortex.Modules.Auth.Entities.User", "User")
                        .WithMany("DripTracks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cortex.Modules.Auth.Entities.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("ContentItems");

                    b.Navigation("DripTracks");

                    b.Navigation("Identities");

                    b.Navigation("Mindset");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Cortex.Modules.Content.Entities.ContentItem", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("ContentItemTags");

                    b.Navigation("DripTracks");

                    b.Navigation("Payload");
                });

            modelBuilder.Entity("Cortex.Modules.Content.Entities.Tag", b =>
                {
                    b.Navigation("ContentItemTags");
                });

            modelBuilder.Entity("Cortex.Modules.Drip.Entities.DripTrack", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
