using Cortex.Shared;

namespace Cortex.Modules.Search.Entities;

public class UserRecommendation : BaseEntity
{
    public Guid UserId { get; set; }
    
    /// <summary>
    /// Type of recommendation: "Content", "Collection", "Trip", "Restaurant", "Product", "FamilyActivity"
    /// </summary>
    public string RecommendationType { get; set; } = string.Empty;
    
    /// <summary>
    /// For content/collection recommendations, this points to the specific item.
    /// </summary>
    public Guid? TargetId { get; set; }
    
    /// <summary>
    /// Title of the recommendation (especially if it's an abstract suggestion).
    /// </summary>
    public string Title { get; set; } = string.Empty;
    
    /// <summary>
    /// Explanation for why this was recommended (e.g., "Because you like Coffee").
    /// </summary>
    public string Reason { get; set; } = string.Empty;
    
    /// <summary>
    /// Score generated by the ML ranking algorithm (higher is better).
    /// </summary>
    public double Score { get; set; }
}
